name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          echo "SSH key has been written to private_key.pem"

      - name: Set up SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Started Redeploying Project"
          ssh -i private_key.pem "$EC2_USER@$EC2_HOST" << 'EOF'
            echo "Deploying Diet Planning and Nutrition Management Application Started" >> /home/ubuntu/deploy-log.txt
            git config --global --add safe.directory /home/ubuntu/Diet-Planning-Nutrition-Management
            cd /home/ubuntu/Diet-Planning-Nutrition-Management || { echo "Failed to change directory"; exit 1; }
            sudo git pull origin main || { echo "Git pull failed"; exit 1; }
            if tmux has-session -t diet_planning 2>/dev/null; then
                tmux kill-session -t diet_planning || { echo "Kill tmux diet_planning session failed"; exit 1; }
            else
                echo "No tmux session named diet_planning found."
            fi
            tmux new-session -d -s diet_planning "cd /home/ubuntu/Diet-Planning-Nutrition-Management && source venv/bin/activate && sudo chown -R \$(whoami) /home/ubuntu/Diet-Planning-Nutrition-Management/venv/lib/python3.12/site-packages/ && sudo chown -R \$USER:\$USER /home/ubuntu/Diet-Planning-Nutrition-Management/venv && pip3 install -r requirements.txt && uvicorn main:app --reload"
            echo "Deploying Diet Planning and Nutrition Management Application Completed" >> /home/ubuntu/deploy-log.txt || { echo "Start server failed"; exit 1; }
          EOF
          echo "Deployment completed successfully"
          rm private_key.pem
